productos.modelo.Producto=productos.repositorio.RepositorioProductosAdHocJPA
productos.modelo.Usuario=productos.repositorio.RepositorioUsuariosAdHocJPA
productos.modelo.Categoria=productos.repositorio.RepositorioCategoriasAdHocJPA