productos.modelo.Producto=productos.repositorio.RepositorioProductosJPA
productos.modelo.Usuario=productos.repositorio.RepositiorioUsuariosJPA
productos.modelo.Categoria=productos.repositorio.RepositorioCategoriasJPA