productos.modelo.Producto=productos.repositorio.RepositorioProductosAdHocJPA
usuarios.modelo.Usuario=usuarios.repositorio.RepositorioUsuariosAdHocJPA
productos.modelo.Categoria=productos.repositorio.RepositorioCategoriasAdHocJPA