spring.application.name=compraventas
server.port=61070
microservicios.usuarios.url=http://localhost:61071/
microservicios.productos.url=http://localhost:61072/
spring.data.mongodb.uri=mongodb://root:example@localhost:27018/compraventas?authSource=admin
#spring.data.mongodb.uri=mongodb+srv://root:root@clusterarso.tubx5zk.mongodb.net/compraventas?appName=ClusterArso?authSource=admin
spring.rabbitmq.addresses=amqp://user:password@localhost:5672
