spring.application.name=compraventas
server.port=8082
microservicios.usuarios.url=http://localhost:8080/users/
microservicios.productos.url=http://localhost:8081/products/
spring.data.mongodb.uri=mongodb://root:example@localhost:27018/compraventas?authSource=admin
#spring.data.mongodb.uri=mongodb+srv://root:root@clusterarso.tubx5zk.mongodb.net/compraventas?appName=ClusterArso