server.port=8090
spring.application.name=pasarela

# Rutas Zuul
# zuul.ignored-services=*
zuul.sensitiveHeaders=
zuul.routes.usuarios.path=/usuarios/**
zuul.routes.usuarios.url=http://localhost:61071/users
# zuul.routes.usuarios.stripPrefix=true
zuul.routes.productos.path=/productos/**
zuul.routes.productos.url=http://localhost:61072/products
# zuul.routes.productos.stripPrefix=true
zuul.routes.compraventas.path=/compraventas/**
zuul.routes.compraventas.url=http://localhost:61070/compraventas
# zuul.routes.compraventas.stripPrefix=true

# URL microservicio usuarios (Retrofit)
usuarios.url=http://localhost:61071

# JWT
jwt.secreto=secreto
jwt.expiracion=3600

# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23liIivcqJXZ7DRcEM
spring.security.oauth2.client.registration.github.client-secret=6bc79a90ac0a4984680ebd81c106f8e534997cc1
